[2023-09-01 18:32:33,095] {processor.py:162} INFO - Started process (PID=3033) to work on /opt/airflow/dags/my_dag.py
[2023-09-01 18:32:33,097] {processor.py:613} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-09-01 18:32:33,098] {logging_mixin.py:109} INFO - [2023-09-01 18:32:33,098] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-09-01 18:32:33,629] {logging_mixin.py:109} WARNING - Resolved './dags/workflow.cwl' to 'file:///opt/airflow/dags/workflow.cwl'
[2023-09-01 18:32:33,629] {logging_mixin.py:109} INFO - [2023-09-01 18:32:33,629] {load_tool.py:101} INFO - Resolved './dags/workflow.cwl' to 'file:///opt/airflow/dags/workflow.cwl'
[2023-09-01 18:32:33,633] {logging_mixin.py:109} INFO - [2023-09-01 18:32:33,631] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1085, in fast_cwl_load
    with open(pickled_workflow, "rb") as input_stream:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/cwl_pickle_folder/d41d8cd98f00b204e9800998ecf8427e.p'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/helpers.py", line 84, in get_uncompressed
    base64.b64decode(
  File "/usr/local/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (17) cannot be 1 more than a multiple of 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1141, in slow_cwl_load
    get_uncompressed(workflow, parse_as_yaml=True),
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/helpers.py", line 90, in get_uncompressed
    base64.b64decode(
  File "/usr/local/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (17) cannot be 1 more than a multiple of 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    dag = CWLDAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/extensions/cwldag.py", line 48, in __init__
    self.workflow_tool = fast_cwl_load(         # keeps only the tool (CommentedMap object)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1090, in fast_cwl_load
    workflow_tool = slow_cwl_load(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1147, in slow_cwl_load
    workflow_data = __load(workflow)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1129, in __load
    return load_tool(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwltool/load_tool.py", line 476, in load_tool
    loadingContext, workflowobj, uri = fetch_document(argsworkflow, loadingContext)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwltool/load_tool.py", line 132, in fetch_document
    loadingContext.loader.fetch(fileuri, content_types=CWL_CONTENT_TYPES),
  File "schema_salad/ref_resolver.py", line 1013, in fetch
StopIteration
[2023-09-01 18:32:33,634] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-09-01 18:32:33,649] {processor.py:170} INFO - Processing /opt/airflow/dags/my_dag.py took 0.558 seconds
[2023-09-01 18:33:03,760] {processor.py:162} INFO - Started process (PID=3051) to work on /opt/airflow/dags/my_dag.py
[2023-09-01 18:33:03,762] {processor.py:613} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-09-01 18:33:03,763] {logging_mixin.py:109} INFO - [2023-09-01 18:33:03,763] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-09-01 18:33:04,222] {logging_mixin.py:109} WARNING - Resolved './dags/workflow.cwl' to 'file:///opt/airflow/dags/workflow.cwl'
[2023-09-01 18:33:04,222] {logging_mixin.py:109} INFO - [2023-09-01 18:33:04,222] {load_tool.py:101} INFO - Resolved './dags/workflow.cwl' to 'file:///opt/airflow/dags/workflow.cwl'
[2023-09-01 18:33:04,226] {logging_mixin.py:109} INFO - [2023-09-01 18:33:04,224] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1085, in fast_cwl_load
    with open(pickled_workflow, "rb") as input_stream:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/cwl_pickle_folder/d41d8cd98f00b204e9800998ecf8427e.p'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/helpers.py", line 84, in get_uncompressed
    base64.b64decode(
  File "/usr/local/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (17) cannot be 1 more than a multiple of 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1141, in slow_cwl_load
    get_uncompressed(workflow, parse_as_yaml=True),
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/helpers.py", line 90, in get_uncompressed
    base64.b64decode(
  File "/usr/local/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (17) cannot be 1 more than a multiple of 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    dag = CWLDAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/extensions/cwldag.py", line 48, in __init__
    self.workflow_tool = fast_cwl_load(         # keeps only the tool (CommentedMap object)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1090, in fast_cwl_load
    workflow_tool = slow_cwl_load(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1147, in slow_cwl_load
    workflow_data = __load(workflow)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1129, in __load
    return load_tool(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwltool/load_tool.py", line 476, in load_tool
    loadingContext, workflowobj, uri = fetch_document(argsworkflow, loadingContext)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwltool/load_tool.py", line 132, in fetch_document
    loadingContext.loader.fetch(fileuri, content_types=CWL_CONTENT_TYPES),
  File "schema_salad/ref_resolver.py", line 1013, in fetch
StopIteration
[2023-09-01 18:33:04,227] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-09-01 18:33:04,244] {processor.py:170} INFO - Processing /opt/airflow/dags/my_dag.py took 0.487 seconds
[2023-09-01 18:33:34,340] {processor.py:162} INFO - Started process (PID=3077) to work on /opt/airflow/dags/my_dag.py
[2023-09-01 18:33:34,342] {processor.py:613} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-09-01 18:33:34,343] {logging_mixin.py:109} INFO - [2023-09-01 18:33:34,343] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-09-01 18:33:34,774] {logging_mixin.py:109} WARNING - Resolved './dags/workflow.cwl' to 'file:///opt/airflow/dags/workflow.cwl'
[2023-09-01 18:33:34,775] {logging_mixin.py:109} INFO - [2023-09-01 18:33:34,774] {load_tool.py:101} INFO - Resolved './dags/workflow.cwl' to 'file:///opt/airflow/dags/workflow.cwl'
[2023-09-01 18:33:34,779] {logging_mixin.py:109} INFO - [2023-09-01 18:33:34,777] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1085, in fast_cwl_load
    with open(pickled_workflow, "rb") as input_stream:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/cwl_pickle_folder/d41d8cd98f00b204e9800998ecf8427e.p'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/helpers.py", line 84, in get_uncompressed
    base64.b64decode(
  File "/usr/local/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (17) cannot be 1 more than a multiple of 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1141, in slow_cwl_load
    get_uncompressed(workflow, parse_as_yaml=True),
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/helpers.py", line 90, in get_uncompressed
    base64.b64decode(
  File "/usr/local/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (17) cannot be 1 more than a multiple of 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    dag = CWLDAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/extensions/cwldag.py", line 48, in __init__
    self.workflow_tool = fast_cwl_load(         # keeps only the tool (CommentedMap object)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1090, in fast_cwl_load
    workflow_tool = slow_cwl_load(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1147, in slow_cwl_load
    workflow_data = __load(workflow)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1129, in __load
    return load_tool(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwltool/load_tool.py", line 476, in load_tool
    loadingContext, workflowobj, uri = fetch_document(argsworkflow, loadingContext)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwltool/load_tool.py", line 132, in fetch_document
    loadingContext.loader.fetch(fileuri, content_types=CWL_CONTENT_TYPES),
  File "schema_salad/ref_resolver.py", line 1013, in fetch
StopIteration
[2023-09-01 18:33:34,780] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-09-01 18:33:34,795] {processor.py:170} INFO - Processing /opt/airflow/dags/my_dag.py took 0.458 seconds
[2023-09-01 18:34:04,901] {processor.py:162} INFO - Started process (PID=3103) to work on /opt/airflow/dags/my_dag.py
[2023-09-01 18:34:04,903] {processor.py:613} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-09-01 18:34:04,904] {logging_mixin.py:109} INFO - [2023-09-01 18:34:04,904] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-09-01 18:34:05,359] {logging_mixin.py:109} WARNING - Resolved './dags/workflow.cwl' to 'file:///opt/airflow/dags/workflow.cwl'
[2023-09-01 18:34:05,360] {logging_mixin.py:109} INFO - [2023-09-01 18:34:05,359] {load_tool.py:101} INFO - Resolved './dags/workflow.cwl' to 'file:///opt/airflow/dags/workflow.cwl'
[2023-09-01 18:34:05,364] {logging_mixin.py:109} INFO - [2023-09-01 18:34:05,362] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1085, in fast_cwl_load
    with open(pickled_workflow, "rb") as input_stream:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/cwl_pickle_folder/d41d8cd98f00b204e9800998ecf8427e.p'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/helpers.py", line 84, in get_uncompressed
    base64.b64decode(
  File "/usr/local/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (17) cannot be 1 more than a multiple of 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1141, in slow_cwl_load
    get_uncompressed(workflow, parse_as_yaml=True),
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/helpers.py", line 90, in get_uncompressed
    base64.b64decode(
  File "/usr/local/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (17) cannot be 1 more than a multiple of 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    dag = CWLDAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/extensions/cwldag.py", line 48, in __init__
    self.workflow_tool = fast_cwl_load(         # keeps only the tool (CommentedMap object)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1090, in fast_cwl_load
    workflow_tool = slow_cwl_load(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1147, in slow_cwl_load
    workflow_data = __load(workflow)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1129, in __load
    return load_tool(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwltool/load_tool.py", line 476, in load_tool
    loadingContext, workflowobj, uri = fetch_document(argsworkflow, loadingContext)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwltool/load_tool.py", line 132, in fetch_document
    loadingContext.loader.fetch(fileuri, content_types=CWL_CONTENT_TYPES),
  File "schema_salad/ref_resolver.py", line 1013, in fetch
StopIteration
[2023-09-01 18:34:05,365] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-09-01 18:34:05,379] {processor.py:170} INFO - Processing /opt/airflow/dags/my_dag.py took 0.481 seconds
[2023-09-01 18:34:35,484] {processor.py:162} INFO - Started process (PID=3121) to work on /opt/airflow/dags/my_dag.py
[2023-09-01 18:34:35,487] {processor.py:613} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-09-01 18:34:35,488] {logging_mixin.py:109} INFO - [2023-09-01 18:34:35,488] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-09-01 18:34:35,919] {logging_mixin.py:109} WARNING - Resolved './dags/workflow.cwl' to 'file:///opt/airflow/dags/workflow.cwl'
[2023-09-01 18:34:35,920] {logging_mixin.py:109} INFO - [2023-09-01 18:34:35,919] {load_tool.py:101} INFO - Resolved './dags/workflow.cwl' to 'file:///opt/airflow/dags/workflow.cwl'
[2023-09-01 18:34:35,922] {logging_mixin.py:109} INFO - [2023-09-01 18:34:35,921] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1085, in fast_cwl_load
    with open(pickled_workflow, "rb") as input_stream:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/cwl_pickle_folder/d41d8cd98f00b204e9800998ecf8427e.p'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/helpers.py", line 84, in get_uncompressed
    base64.b64decode(
  File "/usr/local/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (17) cannot be 1 more than a multiple of 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1141, in slow_cwl_load
    get_uncompressed(workflow, parse_as_yaml=True),
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/helpers.py", line 90, in get_uncompressed
    base64.b64decode(
  File "/usr/local/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (17) cannot be 1 more than a multiple of 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    dag = CWLDAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/extensions/cwldag.py", line 48, in __init__
    self.workflow_tool = fast_cwl_load(         # keeps only the tool (CommentedMap object)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1090, in fast_cwl_load
    workflow_tool = slow_cwl_load(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1147, in slow_cwl_load
    workflow_data = __load(workflow)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1129, in __load
    return load_tool(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwltool/load_tool.py", line 476, in load_tool
    loadingContext, workflowobj, uri = fetch_document(argsworkflow, loadingContext)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwltool/load_tool.py", line 132, in fetch_document
    loadingContext.loader.fetch(fileuri, content_types=CWL_CONTENT_TYPES),
  File "schema_salad/ref_resolver.py", line 1013, in fetch
StopIteration
[2023-09-01 18:34:35,923] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-09-01 18:34:35,939] {processor.py:170} INFO - Processing /opt/airflow/dags/my_dag.py took 0.458 seconds
[2023-09-01 18:35:06,040] {processor.py:162} INFO - Started process (PID=3147) to work on /opt/airflow/dags/my_dag.py
[2023-09-01 18:35:06,042] {processor.py:613} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-09-01 18:35:06,043] {logging_mixin.py:109} INFO - [2023-09-01 18:35:06,043] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-09-01 18:35:06,458] {logging_mixin.py:109} WARNING - Resolved './dags/workflow.cwl' to 'file:///opt/airflow/dags/workflow.cwl'
[2023-09-01 18:35:06,459] {logging_mixin.py:109} INFO - [2023-09-01 18:35:06,458] {load_tool.py:101} INFO - Resolved './dags/workflow.cwl' to 'file:///opt/airflow/dags/workflow.cwl'
[2023-09-01 18:35:06,463] {logging_mixin.py:109} INFO - [2023-09-01 18:35:06,461] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1085, in fast_cwl_load
    with open(pickled_workflow, "rb") as input_stream:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/cwl_pickle_folder/d41d8cd98f00b204e9800998ecf8427e.p'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/helpers.py", line 84, in get_uncompressed
    base64.b64decode(
  File "/usr/local/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (17) cannot be 1 more than a multiple of 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1141, in slow_cwl_load
    get_uncompressed(workflow, parse_as_yaml=True),
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/helpers.py", line 90, in get_uncompressed
    base64.b64decode(
  File "/usr/local/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (17) cannot be 1 more than a multiple of 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    dag = CWLDAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/extensions/cwldag.py", line 48, in __init__
    self.workflow_tool = fast_cwl_load(         # keeps only the tool (CommentedMap object)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1090, in fast_cwl_load
    workflow_tool = slow_cwl_load(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1147, in slow_cwl_load
    workflow_data = __load(workflow)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1129, in __load
    return load_tool(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwltool/load_tool.py", line 476, in load_tool
    loadingContext, workflowobj, uri = fetch_document(argsworkflow, loadingContext)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwltool/load_tool.py", line 132, in fetch_document
    loadingContext.loader.fetch(fileuri, content_types=CWL_CONTENT_TYPES),
  File "schema_salad/ref_resolver.py", line 1013, in fetch
StopIteration
[2023-09-01 18:35:06,466] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-09-01 18:35:06,481] {processor.py:170} INFO - Processing /opt/airflow/dags/my_dag.py took 0.445 seconds
[2023-09-01 18:35:36,582] {processor.py:162} INFO - Started process (PID=3174) to work on /opt/airflow/dags/my_dag.py
[2023-09-01 18:35:36,584] {processor.py:613} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-09-01 18:35:36,585] {logging_mixin.py:109} INFO - [2023-09-01 18:35:36,584] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-09-01 18:35:37,025] {logging_mixin.py:109} WARNING - Resolved './dags/workflow.cwl' to 'file:///opt/airflow/dags/workflow.cwl'
[2023-09-01 18:35:37,025] {logging_mixin.py:109} INFO - [2023-09-01 18:35:37,025] {load_tool.py:101} INFO - Resolved './dags/workflow.cwl' to 'file:///opt/airflow/dags/workflow.cwl'
[2023-09-01 18:35:37,028] {logging_mixin.py:109} INFO - [2023-09-01 18:35:37,027] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1085, in fast_cwl_load
    with open(pickled_workflow, "rb") as input_stream:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/cwl_pickle_folder/d41d8cd98f00b204e9800998ecf8427e.p'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/helpers.py", line 84, in get_uncompressed
    base64.b64decode(
  File "/usr/local/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (17) cannot be 1 more than a multiple of 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1141, in slow_cwl_load
    get_uncompressed(workflow, parse_as_yaml=True),
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/helpers.py", line 90, in get_uncompressed
    base64.b64decode(
  File "/usr/local/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (17) cannot be 1 more than a multiple of 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    dag = CWLDAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/extensions/cwldag.py", line 48, in __init__
    self.workflow_tool = fast_cwl_load(         # keeps only the tool (CommentedMap object)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1090, in fast_cwl_load
    workflow_tool = slow_cwl_load(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1147, in slow_cwl_load
    workflow_data = __load(workflow)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1129, in __load
    return load_tool(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwltool/load_tool.py", line 476, in load_tool
    loadingContext, workflowobj, uri = fetch_document(argsworkflow, loadingContext)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwltool/load_tool.py", line 132, in fetch_document
    loadingContext.loader.fetch(fileuri, content_types=CWL_CONTENT_TYPES),
  File "schema_salad/ref_resolver.py", line 1013, in fetch
StopIteration
[2023-09-01 18:35:37,029] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-09-01 18:35:37,043] {processor.py:170} INFO - Processing /opt/airflow/dags/my_dag.py took 0.465 seconds
[2023-09-01 18:36:07,138] {processor.py:162} INFO - Started process (PID=3192) to work on /opt/airflow/dags/my_dag.py
[2023-09-01 18:36:07,140] {processor.py:613} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-09-01 18:36:07,141] {logging_mixin.py:109} INFO - [2023-09-01 18:36:07,141] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-09-01 18:36:07,564] {logging_mixin.py:109} WARNING - Resolved './dags/workflow.cwl' to 'file:///opt/airflow/dags/workflow.cwl'
[2023-09-01 18:36:07,564] {logging_mixin.py:109} INFO - [2023-09-01 18:36:07,564] {load_tool.py:101} INFO - Resolved './dags/workflow.cwl' to 'file:///opt/airflow/dags/workflow.cwl'
[2023-09-01 18:36:07,568] {logging_mixin.py:109} INFO - [2023-09-01 18:36:07,566] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1085, in fast_cwl_load
    with open(pickled_workflow, "rb") as input_stream:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/cwl_pickle_folder/d41d8cd98f00b204e9800998ecf8427e.p'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/helpers.py", line 84, in get_uncompressed
    base64.b64decode(
  File "/usr/local/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (17) cannot be 1 more than a multiple of 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1141, in slow_cwl_load
    get_uncompressed(workflow, parse_as_yaml=True),
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/helpers.py", line 90, in get_uncompressed
    base64.b64decode(
  File "/usr/local/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (17) cannot be 1 more than a multiple of 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    dag = CWLDAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/extensions/cwldag.py", line 48, in __init__
    self.workflow_tool = fast_cwl_load(         # keeps only the tool (CommentedMap object)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1090, in fast_cwl_load
    workflow_tool = slow_cwl_load(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1147, in slow_cwl_load
    workflow_data = __load(workflow)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1129, in __load
    return load_tool(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwltool/load_tool.py", line 476, in load_tool
    loadingContext, workflowobj, uri = fetch_document(argsworkflow, loadingContext)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwltool/load_tool.py", line 132, in fetch_document
    loadingContext.loader.fetch(fileuri, content_types=CWL_CONTENT_TYPES),
  File "schema_salad/ref_resolver.py", line 1013, in fetch
StopIteration
[2023-09-01 18:36:07,570] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-09-01 18:36:07,585] {processor.py:170} INFO - Processing /opt/airflow/dags/my_dag.py took 0.451 seconds
[2023-09-01 18:36:37,685] {processor.py:162} INFO - Started process (PID=3218) to work on /opt/airflow/dags/my_dag.py
[2023-09-01 18:36:37,686] {processor.py:613} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-09-01 18:36:37,687] {logging_mixin.py:109} INFO - [2023-09-01 18:36:37,686] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-09-01 18:36:38,136] {logging_mixin.py:109} WARNING - Resolved './dags/workflow.cwl' to 'file:///opt/airflow/dags/workflow.cwl'
[2023-09-01 18:36:38,137] {logging_mixin.py:109} INFO - [2023-09-01 18:36:38,136] {load_tool.py:101} INFO - Resolved './dags/workflow.cwl' to 'file:///opt/airflow/dags/workflow.cwl'
[2023-09-01 18:36:38,140] {logging_mixin.py:109} INFO - [2023-09-01 18:36:38,138] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1085, in fast_cwl_load
    with open(pickled_workflow, "rb") as input_stream:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/cwl_pickle_folder/d41d8cd98f00b204e9800998ecf8427e.p'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/helpers.py", line 84, in get_uncompressed
    base64.b64decode(
  File "/usr/local/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (17) cannot be 1 more than a multiple of 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1141, in slow_cwl_load
    get_uncompressed(workflow, parse_as_yaml=True),
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/helpers.py", line 90, in get_uncompressed
    base64.b64decode(
  File "/usr/local/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (17) cannot be 1 more than a multiple of 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    dag = CWLDAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/extensions/cwldag.py", line 48, in __init__
    self.workflow_tool = fast_cwl_load(         # keeps only the tool (CommentedMap object)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1090, in fast_cwl_load
    workflow_tool = slow_cwl_load(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1147, in slow_cwl_load
    workflow_data = __load(workflow)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1129, in __load
    return load_tool(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwltool/load_tool.py", line 476, in load_tool
    loadingContext, workflowobj, uri = fetch_document(argsworkflow, loadingContext)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwltool/load_tool.py", line 132, in fetch_document
    loadingContext.loader.fetch(fileuri, content_types=CWL_CONTENT_TYPES),
  File "schema_salad/ref_resolver.py", line 1013, in fetch
StopIteration
[2023-09-01 18:36:38,141] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-09-01 18:36:38,156] {processor.py:170} INFO - Processing /opt/airflow/dags/my_dag.py took 0.475 seconds
[2023-09-01 18:37:08,246] {processor.py:162} INFO - Started process (PID=3244) to work on /opt/airflow/dags/my_dag.py
[2023-09-01 18:37:08,248] {processor.py:613} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-09-01 18:37:08,248] {logging_mixin.py:109} INFO - [2023-09-01 18:37:08,248] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-09-01 18:37:08,678] {logging_mixin.py:109} WARNING - Resolved './dags/workflow.cwl' to 'file:///opt/airflow/dags/workflow.cwl'
[2023-09-01 18:37:08,678] {logging_mixin.py:109} INFO - [2023-09-01 18:37:08,678] {load_tool.py:101} INFO - Resolved './dags/workflow.cwl' to 'file:///opt/airflow/dags/workflow.cwl'
[2023-09-01 18:37:08,681] {logging_mixin.py:109} INFO - [2023-09-01 18:37:08,679] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1085, in fast_cwl_load
    with open(pickled_workflow, "rb") as input_stream:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/cwl_pickle_folder/d41d8cd98f00b204e9800998ecf8427e.p'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/helpers.py", line 84, in get_uncompressed
    base64.b64decode(
  File "/usr/local/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (17) cannot be 1 more than a multiple of 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1141, in slow_cwl_load
    get_uncompressed(workflow, parse_as_yaml=True),
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/helpers.py", line 90, in get_uncompressed
    base64.b64decode(
  File "/usr/local/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (17) cannot be 1 more than a multiple of 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    dag = CWLDAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/extensions/cwldag.py", line 48, in __init__
    self.workflow_tool = fast_cwl_load(         # keeps only the tool (CommentedMap object)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1090, in fast_cwl_load
    workflow_tool = slow_cwl_load(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1147, in slow_cwl_load
    workflow_data = __load(workflow)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1129, in __load
    return load_tool(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwltool/load_tool.py", line 476, in load_tool
    loadingContext, workflowobj, uri = fetch_document(argsworkflow, loadingContext)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwltool/load_tool.py", line 132, in fetch_document
    loadingContext.loader.fetch(fileuri, content_types=CWL_CONTENT_TYPES),
  File "schema_salad/ref_resolver.py", line 1013, in fetch
StopIteration
[2023-09-01 18:37:08,682] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-09-01 18:37:08,696] {processor.py:170} INFO - Processing /opt/airflow/dags/my_dag.py took 0.453 seconds
[2023-09-01 18:37:38,801] {processor.py:162} INFO - Started process (PID=3262) to work on /opt/airflow/dags/my_dag.py
[2023-09-01 18:37:38,803] {processor.py:613} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-09-01 18:37:38,804] {logging_mixin.py:109} INFO - [2023-09-01 18:37:38,804] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-09-01 18:37:39,303] {logging_mixin.py:109} WARNING - Resolved './dags/workflow.cwl' to 'file:///opt/airflow/dags/workflow.cwl'
[2023-09-01 18:37:39,304] {logging_mixin.py:109} INFO - [2023-09-01 18:37:39,303] {load_tool.py:101} INFO - Resolved './dags/workflow.cwl' to 'file:///opt/airflow/dags/workflow.cwl'
[2023-09-01 18:37:39,308] {logging_mixin.py:109} INFO - [2023-09-01 18:37:39,305] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1085, in fast_cwl_load
    with open(pickled_workflow, "rb") as input_stream:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/cwl_pickle_folder/d41d8cd98f00b204e9800998ecf8427e.p'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/helpers.py", line 84, in get_uncompressed
    base64.b64decode(
  File "/usr/local/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (17) cannot be 1 more than a multiple of 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1141, in slow_cwl_load
    get_uncompressed(workflow, parse_as_yaml=True),
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/helpers.py", line 90, in get_uncompressed
    base64.b64decode(
  File "/usr/local/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (17) cannot be 1 more than a multiple of 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    dag = CWLDAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/extensions/cwldag.py", line 48, in __init__
    self.workflow_tool = fast_cwl_load(         # keeps only the tool (CommentedMap object)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1090, in fast_cwl_load
    workflow_tool = slow_cwl_load(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1147, in slow_cwl_load
    workflow_data = __load(workflow)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwl_airflow/utilities/cwl.py", line 1129, in __load
    return load_tool(
  File "/home/airflow/.local/lib/python3.8/site-packages/cwltool/load_tool.py", line 476, in load_tool
    loadingContext, workflowobj, uri = fetch_document(argsworkflow, loadingContext)
  File "/home/airflow/.local/lib/python3.8/site-packages/cwltool/load_tool.py", line 132, in fetch_document
    loadingContext.loader.fetch(fileuri, content_types=CWL_CONTENT_TYPES),
  File "schema_salad/ref_resolver.py", line 1013, in fetch
StopIteration
[2023-09-01 18:37:39,310] {processor.py:625} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-09-01 18:37:39,326] {processor.py:170} INFO - Processing /opt/airflow/dags/my_dag.py took 0.528 seconds
